schema_version = "1.0.0"

id = "virtucamera_blender"
version = "1.3.0"
name = "VirtuCamera"
tagline = "Stream your Blender viewport to the VirtuCamera mobile app"
maintainer = "festivity"
type = "add-on"

platforms = ["windows-x64"]

[permissions]
network = "Communicate with the VirtuCamera mobile app over local network"
